services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
    command: ["start-dev"]
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-providers:/opt/keycloak/providers
    networks:
      - fsa-network

networks:
  fsa-network:
    driver: bridge
